// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22b57fa5DecodeGithubComAler1anGoLabsLab06Models(in *jlexer.Lexer, out *Server) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "host":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Host = string(in.String())
			}
		case "port":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Port = int(in.Int())
			}
		case "debug":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Debug = bool(in.Bool())
			}
		case "allowed_ips":
			if in.IsNull() {
				in.Skip()
				out.AllowedIPs = nil
			} else {
				in.Delim('[')
				if out.AllowedIPs == nil {
					if !in.IsDelim(']') {
						out.AllowedIPs = make([]string, 0, 4)
					} else {
						out.AllowedIPs = []string{}
					}
				} else {
					out.AllowedIPs = (out.AllowedIPs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.AllowedIPs = append(out.AllowedIPs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b57fa5EncodeGithubComAler1anGoLabsLab06Models(out *jwriter.Writer, in Server) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"host\":"
		out.RawString(prefix[1:])
		out.String(string(in.Host))
	}
	{
		const prefix string = ",\"port\":"
		out.RawString(prefix)
		out.Int(int(in.Port))
	}
	{
		const prefix string = ",\"debug\":"
		out.RawString(prefix)
		out.Bool(bool(in.Debug))
	}
	{
		const prefix string = ",\"allowed_ips\":"
		out.RawString(prefix)
		if in.AllowedIPs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.AllowedIPs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Server) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b57fa5EncodeGithubComAler1anGoLabsLab06Models(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Server) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b57fa5EncodeGithubComAler1anGoLabsLab06Models(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Server) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b57fa5DecodeGithubComAler1anGoLabsLab06Models(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Server) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b57fa5DecodeGithubComAler1anGoLabsLab06Models(l, v)
}
